Add controllers
Primorets/java-shareit pull request #1
Opened 2023-04-18 18:00 UTC by Primorets

2023-04-19 15:21 UTC, sergeymamonov requested changes

2023-04-19 15:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/UserNotFoundException.java
> +public class UserNotFoundException extends IllegalArgumentException {
А почему унаследовались от IllegalArgumentException? Можно проще, можно все исключения в этом пакете унаследовать от RuntimeException.

2023-04-19 15:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    }
Можно еще добавить ошибку времени выполнения и вернуть 500 статус.

2023-04-19 15:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +    private HashMap<Integer, Item> itemsMap;
Тип нужно определять на уровне интерфейса, то есть Map<Integer, Item> items.

2023-04-19 15:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
Можно конечно и так, но по отношению к пользователю это не дружелюбно. То есть пользователь в запросе указал много разных полей и получает ответ, что что-то неверно. И ему самому нужно разбираться, что именно неверно.

2023-04-19 15:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +    private HashMap<Integer, User> usersMap;
Использовать интерфейс.

2023-04-24 19:01 UTC, Primorets commented on src/main/java/ru/practicum/shareit/exception/UserNotFoundException.java
> +public class UserNotFoundException extends IllegalArgumentException {
Исправлено. Спасибо.

2023-04-24 19:01 UTC, Primorets commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    }
Добавлено.

2023-04-24 19:01 UTC, Primorets commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +    private HashMap<Integer, Item> itemsMap;
Исправлено.

2023-04-24 19:02 UTC, Primorets commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
Исправлено.

2023-04-24 19:02 UTC, Primorets commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +    private HashMap<Integer, User> usersMap;
Исправлено.

2023-04-25 09:50 UTC, sergeymamonov approved these changes

2023-05-01 08:08 UTC, merged